const CRYSTALS=[
  {name:"Lapis Lazuli",it:"Lapislazzuli",emoji:"💙",lunar:"Lascia il lapislazzuli sotto la luna piena per 8 ore per ricaricare la sua energia di saggezza e verità.",lunarEn:"Leave lapis lazuli under the full moon for 8 hours to recharge its wisdom and truth energy.",words:[
    {en:"moonlight",it:"luce della luna",ex:"The moonlight is beautiful tonight."},
    {en:"wisdom",it:"saggezza",ex:"Lapis gives wisdom to the mind."},
    {en:"peace",it:"pace",ex:"I feel peace when I hold this crystal."},
    {en:"healing",it:"guarigione",ex:"Crystals have healing power."},
    {en:"truth",it:"verità",ex:"Lapis reveals the truth."},
    {en:"ancient",it:"antico",ex:"Lapis lazuli is an ancient stone."},
    {en:"celestial",it:"celeste / celestiale",ex:"The stars have a celestial beauty."},
    {en:"profound",it:"profondo",ex:"She has a profound knowledge of crystals."},
    {en:"illuminate",it:"illuminare",ex:"Let the truth illuminate your path."},
    {en:"sacred",it:"sacro",ex:"This place feels deeply sacred."},
  ]},
  {name:"Topaz",it:"Topazio",emoji:"✨",lunar:"Il topazio si carica con la luna crescente — mettilo sul davanzale quando la luna inizia a crescere.",lunarEn:"Topaz charges with the waxing moon — put it on the windowsill as the moon starts to grow.",words:[
    {en:"strength",it:"forza",ex:"Topaz gives you inner strength."},
    {en:"clarity",it:"chiarezza",ex:"Find clarity with this stone."},
    {en:"energy",it:"energia",ex:"Feel the energy of topaz."},
    {en:"joy",it:"gioia",ex:"Topaz brings joy to your heart."},
    {en:"bright",it:"luminoso",ex:"The stone is very bright."},
    {en:"radiant",it:"raggiante",ex:"She looks absolutely radiant today."},
    {en:"confidence",it:"fiducia in sé",ex:"Topaz boosts your confidence."},
    {en:"vibrant",it:"vibrante",ex:"The color is vivid and vibrant."},
    {en:"uplift",it:"sollevare / tirare su",ex:"This crystal will uplift your mood."},
    {en:"golden",it:"dorato",ex:"The topaz has a beautiful golden hue."},
  ]},
  {name:"Amethyst",it:"Ametista",emoji:"💜",lunar:"L'ametista assorbe l'energia della luna calante. Meditaci sopra di notte per purificare i sogni.",lunarEn:"Amethyst absorbs waning moon energy. Meditate with it at night to purify your dreams.",words:[
    {en:"calm",it:"calma",ex:"Amethyst brings calm to the room."},
    {en:"dream",it:"sogno",ex:"Place it by your bed for good dreams."},
    {en:"balance",it:"equilibrio",ex:"Find your balance every day."},
    {en:"protect",it:"proteggere",ex:"This crystal protects your energy."},
    {en:"spiritual",it:"spirituale",ex:"This is a very spiritual stone."},
    {en:"meditate",it:"meditare",ex:"I meditate with amethyst every night."},
    {en:"tranquil",it:"tranquillo",ex:"The room feels tranquil and safe."},
    {en:"awareness",it:"consapevolezza",ex:"Meditation increases self-awareness."},
    {en:"soothe",it:"calmare",ex:"This crystal helps soothe anxiety."},
    {en:"restful",it:"riposante",ex:"I had the most restful sleep ever."},
  ]},
  {name:"Rose Quartz",it:"Quarzo Rosa",emoji:"🌸",lunar:"Il quarzo rosa si potenzia sotto la luna in Bilancia o Toro — attira l'amore e l'armonia.",lunarEn:"Rose quartz amplifies under the Libra or Taurus moon — it attracts love and harmony.",words:[
    {en:"love",it:"amore",ex:"Rose quartz attracts love."},
    {en:"gentle",it:"gentile",ex:"The energy is very gentle."},
    {en:"heart",it:"cuore",ex:"It opens your heart."},
    {en:"harmony",it:"armonia",ex:"Feel the harmony around you."},
    {en:"kindness",it:"gentilezza",ex:"Kindness is a superpower."},
    {en:"compassion",it:"compassione",ex:"She shows great compassion for others."},
    {en:"tender",it:"tenero",ex:"His voice was so tender and warm."},
    {en:"soft",it:"morbido / delicato",ex:"The energy of rose quartz is soft."},
    {en:"romantic",it:"romantico",ex:"The atmosphere was so romantic."},
    {en:"nurture",it:"nutrire / prendersi cura",ex:"Nurture your heart every single day."},
  ]},
  {name:"Moonstone",it:"Pietra di Luna",emoji:"🌙",lunar:"La pietra di luna è MAGICA durante la luna piena. Portala sempre con te quella notte speciale!",lunarEn:"Moonstone is MAGICAL during the full moon. Always carry it with you on that special night!",words:[
    {en:"intuition",it:"intuizione",ex:"Trust your intuition always."},
    {en:"cycle",it:"ciclo",ex:"The moon has a monthly cycle."},
    {en:"mystery",it:"mistero",ex:"The stone is full of mystery."},
    {en:"glow",it:"bagliore",ex:"Look at that beautiful glow!"},
    {en:"inner",it:"interiore",ex:"Find your inner light."},
    {en:"ethereal",it:"etereo",ex:"Moonstone has an ethereal shimmer."},
    {en:"lunar",it:"lunare",ex:"The lunar energy is strongest tonight."},
    {en:"feminine",it:"femminile",ex:"It carries a deeply feminine energy."},
    {en:"pearl",it:"perla",ex:"The stone shines like a pearl."},
    {en:"enchanting",it:"incantevole",ex:"The moonstone is truly enchanting."},
  ]},
  {name:"Citrine",it:"Citrino",emoji:"🌟",lunar:"Il citrino si carica con la luna nuova — è il momento perfetto per fissare nuove intenzioni di prosperità.",lunarEn:"Citrine charges with the new moon — the perfect time to set new intentions of prosperity.",words:[
    {en:"abundance",it:"abbondanza",ex:"Citrine attracts abundance."},
    {en:"prosperity",it:"prosperità",ex:"Feel the energy of prosperity."},
    {en:"sunny",it:"soleggiato",ex:"Citrine has a sunny warm energy."},
    {en:"manifest",it:"manifestare",ex:"Manifest your dreams right now."},
    {en:"positive",it:"positivo",ex:"Stay positive every single day."},
    {en:"cheerful",it:"allegro",ex:"She has such a cheerful personality."},
    {en:"grateful",it:"grata / riconoscente",ex:"I am grateful for everything I have."},
    {en:"flourish",it:"fiorire / prosperare",ex:"You will flourish in your new life."},
    {en:"attract",it:"attrarre",ex:"Good energy attracts good things."},
    {en:"optimism",it:"ottimismo",ex:"Face every day with optimism."},
  ]},
  {name:"Obsidian",it:"Ossidiana",emoji:"🖤",lunar:"L'ossidiana assorbe le energie negative durante la luna calante. Puliscila spesso sotto l'acqua corrente.",lunarEn:"Obsidian absorbs negative energies during the waning moon. Clean it often under running water.",words:[
    {en:"shadow",it:"ombra",ex:"Face your shadow with courage."},
    {en:"release",it:"lasciar andare",ex:"Release what no longer serves you."},
    {en:"grounding",it:"radicamento",ex:"Obsidian is deeply grounding."},
    {en:"volcanic",it:"vulcanico",ex:"Obsidian is natural volcanic glass."},
    {en:"shield",it:"scudo",ex:"It acts as a protective shield."},
    {en:"absorb",it:"assorbire",ex:"Obsidian absorbs negative energy."},
    {en:"depth",it:"profondità",ex:"The stone has great emotional depth."},
    {en:"raw",it:"grezzo / puro",ex:"She showed her raw, true self."},
    {en:"powerful",it:"potente",ex:"This is a very powerful crystal."},
    {en:"purify",it:"purificare",ex:"Use obsidian to purify your space."},
  ]},
  {name:"Tiger's Eye",it:"Occhio di Tigre",emoji:"🐯",lunar:"L'occhio di tigre si potenzia con la luna crescente — porta coraggio nei momenti più difficili.",lunarEn:"Tiger's eye amplifies with the waxing moon — it brings courage in the hardest moments.",words:[
    {en:"courage",it:"coraggio",ex:"Have the courage to be yourself."},
    {en:"focus",it:"concentrazione",ex:"Tiger's eye improves your focus."},
    {en:"bold",it:"audace",ex:"Be bold and fearless today."},
    {en:"fierce",it:"intenso",ex:"She has such a fierce energy."},
    {en:"determined",it:"determinato",ex:"Stay determined no matter what."},
    {en:"fearless",it:"senza paura",ex:"Be fearless and trust yourself."},
    {en:"willpower",it:"forza di volontà",ex:"You have incredible willpower."},
    {en:"steadfast",it:"saldo / fedele",ex:"She remained steadfast in her goals."},
    {en:"warrior",it:"guerriero / guerriera",ex:"She is a true warrior of light."},
    {en:"tenacious",it:"tenace",ex:"She is the most tenacious person I know."},
  ]},
  {name:"Selenite",it:"Selenite",emoji:"🤍",lunar:"La selenite è l'unica pietra che non ha bisogno di essere caricata — contiene già la luce della luna.",lunarEn:"Selenite is the only stone that doesn't need charging — it already contains moonlight within itself.",words:[
    {en:"pure",it:"puro",ex:"Selenite has a pure white energy."},
    {en:"cleanse",it:"purificare",ex:"Use selenite to cleanse your space."},
    {en:"angelic",it:"angelico",ex:"It carries an angelic vibration."},
    {en:"serene",it:"sereno",ex:"The energy is calm and serene."},
    {en:"divine",it:"divino",ex:"Feel the divine light within you."},
    {en:"luminous",it:"luminoso",ex:"The stone is soft and luminous."},
    {en:"translucent",it:"traslucido",ex:"Selenite is beautifully translucent."},
    {en:"holy",it:"sacro / santo",ex:"This place carries a holy energy."},
    {en:"white",it:"bianco",ex:"Selenite is a beautiful white crystal."},
    {en:"peaceful",it:"pacifico / sereno",ex:"I feel so peaceful holding selenite."},
  ]},
  {name:"Labradorite",it:"Labradorite",emoji:"🦋",lunar:"La labradorite brilla come la luna — mostra colori diversi a seconda della luce, come le nostre emozioni.",lunarEn:"Labradorite shines like the moon — it shows different colors depending on the light, just like our emotions.",words:[
    {en:"transform",it:"trasformare",ex:"She began to transform herself."},
    {en:"magical",it:"magico",ex:"Labradorite has a magical glow."},
    {en:"iridescent",it:"iridescente",ex:"The stone is iridescent and stunning."},
    {en:"awaken",it:"risvegliare",ex:"Awaken your true inner potential."},
    {en:"beyond",it:"oltre",ex:"Look beyond what you can see."},
    {en:"mystical",it:"mistico",ex:"The stone has a mystical quality."},
    {en:"shimmer",it:"luccicare / brillare",ex:"The stone shimmers in the light."},
    {en:"evolve",it:"evolversi",ex:"We are always evolving and growing."},
    {en:"wonder",it:"meraviglia",ex:"Look at the world with wonder."},
    {en:"potential",it:"potenziale",ex:"You have incredible untapped potential."},
  ]},
];

const ZODIAC=[
  {sign:"Aries",it:"Ariete",emoji:"♈",dates:"21 Mar – 19 Apr",traits:["brave","energetic","bold","leader","passionate"],itTraits:["coraggioso","energico","audace","leader","appassionato"],element:"Fuoco 🔥",crystal:"Red Jasper 🔴",tip:"Say 'I am brave' every morning!",deep:"L'Ariete è il primo segno dello zodiaco — pieno di energia e voglia di iniziare nuove cose. Non ha paura di niente e va sempre avanti.",deepEn:"Aries is the first sign — full of energy and desire to start new things. It fears nothing and always moves forward."},
  {sign:"Taurus",it:"Toro",emoji:"♉",dates:"20 Apr – 20 May",traits:["loyal","patient","strong","sensual","reliable"],itTraits:["leale","paziente","forte","sensuale","affidabile"],element:"Terra 🌍",crystal:"Rose Quartz 🌸",tip:"Your English word: 'steadfast' = saldo, fedele.",deep:"Il Toro ama il bello, il comfort e la stabilità. È il segno più sensuale dello zodiaco.",deepEn:"Taurus loves beauty, comfort and stability. It's the most sensual sign of the zodiac."},
  {sign:"Gemini",it:"Gemelli",emoji:"♊",dates:"21 May – 20 Jun",traits:["curious","clever","social","fun","adaptable"],itTraits:["curioso","intelligente","sociale","divertente","adattabile"],element:"Aria 💨",crystal:"Citrine 💛",tip:"Gemini loves to talk — perfect for learning English!",deep:"I Gemelli hanno due anime — sociali e riservati allo stesso tempo. Adorano imparare cose nuove.",deepEn:"Gemini has two souls — social and reserved at the same time. They love learning new things."},
  {sign:"Cancer",it:"Cancro",emoji:"♋",dates:"21 Jun – 22 Jul",traits:["caring","sensitive","intuitive","nurturing","creative"],itTraits:["premuroso","sensibile","intuitivo","materno","creativo"],element:"Acqua 💧",crystal:"Moonstone 🌙",tip:"Your power word: 'nurture' = prendersi cura.",deep:"Il Cancro è governato dalla Luna — profondo e intuitivo. Ha un'enorme capacità di amare e proteggere.",deepEn:"Cancer is ruled by the Moon — deep and intuitive. It has an enormous capacity to love and protect."},
  {sign:"Leo",it:"Leone",emoji:"♌",dates:"23 Jul – 22 Aug",traits:["confident","creative","warm","royal","generous"],itTraits:["sicuro","creativo","caldo","regale","generoso"],element:"Fuoco 🔥",crystal:"Sunstone ☀️",tip:"Say 'I am radiant' — it means raggiante!",deep:"Il Leone ama brillare e far sentire speciali le persone che ama. Ha un cuore grandissimo.",deepEn:"Leo loves to shine and make people it loves feel special. It has a huge heart."},
  {sign:"Virgo",it:"Vergine",emoji:"♍",dates:"23 Aug – 22 Sep",traits:["smart","helpful","careful","gentle","precise"],itTraits:["intelligente","utile","attento","gentile","preciso"],element:"Terra 🌍",crystal:"Amazonite 💚",tip:"Your word: 'meticulous' = meticoloso. Very Virgo!",deep:"La Vergine vede i dettagli che gli altri non notano. Si sente bene quando aiuta e migliora le cose.",deepEn:"Virgo sees details others miss. It feels good when it helps and improves things."},
  {sign:"Libra",it:"Bilancia",emoji:"♎",dates:"23 Sep – 22 Oct",traits:["fair","peaceful","charming","balanced","elegant"],itTraits:["giusto","pacifico","affascinante","equilibrato","elegante"],element:"Aria 💨",crystal:"Lapis Lazuli 💙",tip:"'Aesthetic' is your English word — you know it!",deep:"La Bilancia è governata da Venere — ama la bellezza, l'armonia e le relazioni.",deepEn:"Libra is ruled by Venus — it loves beauty, harmony and relationships."},
  {sign:"Scorpio",it:"Scorpione",emoji:"♏",dates:"23 Oct – 21 Nov",traits:["intense","passionate","deep","powerful","loyal"],itTraits:["intenso","appassionato","profondo","potente","leale"],element:"Acqua 💧",crystal:"Obsidian 🖤",tip:"Your word: 'magnetic' = magnetico. Very Scorpio!",deep:"Lo Scorpione è il segno della trasformazione — muore e rinasce come la fenice.",deepEn:"Scorpio is the sign of transformation — it dies and is reborn like a phoenix."},
  {sign:"Sagittarius",it:"Sagittario",emoji:"♐",dates:"22 Nov – 21 Dec",
   traits:["free","adventurous","honest","wise","optimistic","curious","funny","generous"],
   itTraits:["libero","avventuroso","onesto","saggio","ottimista","curioso","divertente","generoso"],
   element:"Fuoco 🔥",crystal:"Turquoise 🩵",tip:"'Wanderlust' = voglia di viaggiare. La parola più Sagittario!",
   isEmanuela:true,
   planet:"Giove (Jupiter) 🪐 — il pianeta della fortuna e dell'espansione!",planetEn:"Jupiter 🪐 — the planet of luck and expansion!",
   deep:"Il Sagittario è il filosofo e l'avventuriero dello zodiaco. Ama la libertà sopra ogni cosa — non sopporta le catene. È brutalmente onesto e dice sempre quello che pensa. Ama viaggiare, imparare lingue nuove e scoprire culture diverse. Giove gli porta fortuna naturale!",
   deepEn:"Sagittarius is the philosopher and adventurer of the zodiac. It loves freedom above all. It's brutally honest and always says what it thinks. It loves traveling, learning new languages and discovering different cultures. Jupiter brings natural luck!",
   compatible:["Ariete ♈","Leone ♌","Acquario ♒","Bilancia ♎"],
   celebrities:["Taylor Swift 🎵","Miley Cyrus 🎤","Billie Eilish 🖤","Brad Pitt 🎬","Nicki Minaj 👑"],
   shadowTraits:["impatient","restless","blunt","commitment-phobic"],shadowIt:["impaziente","irrequieto","brusco","evita gli impegni"],
   powerWord:"'Expansive' = espansivo. La parola perfetta per l'energia del Sagittario — sempre più grande, sempre più lontano!",
  },
  {sign:"Capricorn",it:"Capricorno",emoji:"♑",dates:"22 Dec – 19 Jan",traits:["responsible","ambitious","wise","disciplined","patient"],itTraits:["responsabile","ambizioso","saggio","disciplinato","paziente"],element:"Terra 🌍",crystal:"Garnet ❤️",tip:"'Resilient' = resiliente. Your superpower!",deep:"Il Capricorno scala la montagna della vita con pazienza e determinazione. Non si ferma mai.",deepEn:"Capricorn climbs the mountain of life with patience and determination. It never stops."},
  {sign:"Aquarius",it:"Acquario",emoji:"♒",dates:"20 Jan – 18 Feb",traits:["unique","open-minded","kind","original","visionary"],itTraits:["unico","aperto","gentile","originale","visionario"],element:"Aria 💨",crystal:"Amethyst 💜",tip:"'Revolutionary' — that's your energy!",deep:"L'Acquario è il segno del futuro — pensa in modo originale e vuole cambiare il mondo.",deepEn:"Aquarius is the sign of the future — it thinks originally and wants to change the world."},
  {sign:"Pisces",it:"Pesci",emoji:"♓",dates:"19 Feb – 20 Mar",traits:["dreamy","artistic","kind","spiritual","empathetic"],itTraits:["sognante","artistico","gentile","spirituale","empatico"],element:"Acqua 💧",crystal:"Aquamarine 🩵",tip:"'Ethereal' = etereo. The most Pisces word ever.",deep:"I Pesci vivono tra realtà e sogno. Sono i più empatici dello zodiaco.",deepEn:"Pisces lives between reality and dream. They are the most empathetic of the zodiac."},
];

const FACTS=[
  {emoji:"🍋",title:"Limone & Spaghetti",titleEn:"Lemon & Spaghetti",fact:"Sapevi che 'zesty' significa piena di sapore e vivacità? Si usa spesso per i piatti col limone! E 'squeeze' vuol dire strizzare — esattamente quello che si fa col limone sulla pasta.",factEn:"'Zesty' means full of flavor and liveliness — often used for lemon dishes. 'Squeeze' means strizzare — exactly what you do with a lemon on pasta!",words:[
    {en:"lemon",it:"limone",ex:"This pasta has fresh lemon!"},
    {en:"zesty",it:"saporito / vivace",ex:"This dish is incredibly zesty."},
    {en:"squeeze",it:"strizzare",ex:"Squeeze the lemon over the pasta."},
    {en:"recipe",it:"ricetta",ex:"Can you share your recipe?"},
    {en:"delicious",it:"delizioso",ex:"This is absolutely delicious!"},
    {en:"flavor",it:"sapore / gusto",ex:"The flavor of this dish is amazing."},
    {en:"ingredient",it:"ingrediente",ex:"What are the ingredients?"},
    {en:"simmer",it:"cuocere a fuoco lento",ex:"Let the sauce simmer for ten minutes."},
  ]},
  {emoji:"🌊",title:"La Spiaggia",titleEn:"The Beach",fact:"'Shore' e 'coast' sono sinonimi di riva/costa. 'Beach' è la parte sabbiosa. 'Tide' è la marea — 'high tide' è alta marea, 'low tide' è bassa marea. 'Driftwood' è il legno trascinato dal mare.",factEn:"'Shore' and 'coast' both mean riva/costa. 'Beach' is the sandy part. 'Tide' is marea — 'high tide' is alta marea, 'low tide' is bassa marea.",words:[
    {en:"wave",it:"onda",ex:"Look at that enormous wave!"},
    {en:"shore",it:"riva",ex:"Let's walk along the shore."},
    {en:"tide",it:"marea",ex:"The tide is coming in."},
    {en:"sunset",it:"tramonto",ex:"The sunset is pink and stunning."},
    {en:"seashell",it:"conchiglia",ex:"I found a beautiful seashell today."},
    {en:"sandy",it:"sabbioso",ex:"The sandy beach stretches for miles."},
    {en:"ocean",it:"oceano",ex:"The ocean is vast and beautiful."},
    {en:"horizon",it:"orizzonte",ex:"The sun disappears below the horizon."},
  ]},
  {emoji:"🪢",title:"Le Treccine",titleEn:"Box Braids",fact:"Le box braids hanno più di 5000 anni di storia in Africa! 'Braids' sono le trecce, 'protective style' è un'acconciatura che protegge i capelli. Guardare le trecce intrecciarsi ha un effetto meditativo.",factEn:"Box braids have over 5000 years of history in Africa! 'Braids' = trecce, 'protective style' = a hairstyle that protects hair. Watching the weaving pattern has a meditative effect.",words:[
    {en:"braids",it:"treccine",ex:"Your braids look absolutely amazing!"},
    {en:"weave",it:"intrecciare",ex:"She can weave hair so beautifully."},
    {en:"protective",it:"protettivo",ex:"It's a very protective style."},
    {en:"cultural",it:"culturale",ex:"It's a deep cultural tradition."},
    {en:"elegant",it:"elegante",ex:"So elegant and timeless!"},
    {en:"heritage",it:"patrimonio / eredità culturale",ex:"Braids are part of African heritage."},
    {en:"stunning",it:"mozzafiato",ex:"Your new look is absolutely stunning."},
    {en:"style",it:"stile",ex:"She has an incredible personal style."},
  ]},
  {emoji:"🧘",title:"Pilates in Inglese",titleEn:"Pilates in English",fact:"Il pilates è stato inventato da Joseph Pilates negli anni '20 in Germania! Le istruzioni nelle classi sono quasi sempre in inglese. La parola più importante? 'Core' — il centro del corpo. Senza core non si fa pilates!",factEn:"Pilates was invented by Joseph Pilates in the 1920s in Germany! Class instructions are almost always in English. The most important word? 'Core' — the body's center. No core, no pilates!",words:[
    {en:"breathe",it:"respirare",ex:"Breathe in slowly and deeply."},
    {en:"core",it:"addominali / centro",ex:"Engage your core right now!"},
    {en:"lengthen",it:"allungare",ex:"Lengthen your spine up tall."},
    {en:"posture",it:"postura",ex:"Your posture looks perfect!"},
    {en:"flow",it:"fluidità",ex:"Move with flow and grace."},
    {en:"engage",it:"attivare / contrarre",ex:"Engage your core and breathe."},
    {en:"inhale",it:"inspirare",ex:"Inhale through your nose slowly."},
    {en:"tuck",it:"inclinare / portare dentro",ex:"Tuck your chin slightly forward."},
  ]},
  {emoji:"🏋️",title:"Attrezzatura Pilates",titleEn:"Pilates Equipment",fact:"Il pilates non è solo tappetino! Il 'reformer' è la macchina più famosa — un lettino con molle e cinghie. Il 'magic circle' o 'ring' si tiene tra le ginocchia o le braccia per creare resistenza. Conoscere questi nomi ti aiuta con i video YouTube!",factEn:"Pilates is not just a mat! The 'reformer' is the most famous machine — a bed with springs and straps. The 'magic circle' or 'ring' is held between knees or arms for resistance. Knowing these names helps with YouTube videos!",words:[
    {en:"reformer",it:"reformer (macchina pilates)",ex:"The reformer class was amazing!"},
    {en:"resistance",it:"resistenza",ex:"Increase the resistance slowly."},
    {en:"neutral spine",it:"colonna in posizione neutra",ex:"Keep a neutral spine always."},
    {en:"alignment",it:"allineamento",ex:"Check your body alignment."},
    {en:"controlled",it:"controllato",ex:"Every movement must be controlled."},
    {en:"mat",it:"tappetino",ex:"Roll out your mat on the floor."},
    {en:"spring",it:"molla",ex:"Add another spring for more resistance."},
    {en:"rep",it:"ripetizione",ex:"Do ten reps on each side."},
  ]},
  {emoji:"🧠",title:"Psicologia",titleEn:"Psychology",fact:"La psicologia usa tantissime parole inglesi che sentiamo ogni giorno! 'Boundaries' (confini personali) è forse la più importante — saper dire no è fondamentale. 'Gaslighting', 'toxic', 'trigger' — tutte dall'inglese!",factEn:"Psychology uses many English words we hear daily! 'Boundaries' is perhaps the most important — knowing how to say no is essential. 'Gaslighting', 'toxic', 'trigger' — all from English!",words:[
    {en:"anxiety",it:"ansia",ex:"I sometimes feel anxiety."},
    {en:"boundary",it:"confine / limite",ex:"I need to set my boundaries."},
    {en:"resilience",it:"resilienza",ex:"She has incredible resilience."},
    {en:"healing",it:"guarigione / cura di sé",ex:"I am healing every single day."},
    {en:"empathy",it:"empatia",ex:"She shows so much empathy."},
    {en:"trigger",it:"scatenare / far scattare",ex:"That comment triggered a strong reaction."},
    {en:"toxic",it:"tossico",ex:"Leave toxic situations behind you."},
    {en:"mindset",it:"mentalità",ex:"Change your mindset, change your life."},
  ]},
  {emoji:"🔗",title:"Stili di Attaccamento",titleEn:"Attachment Styles",fact:"La teoria degli stili di attaccamento è fondamentale in psicologia! 'Secure' (sicuro) è il tipo sano. 'Anxious' è quando hai paura di perdere le persone. 'Avoidant' è quando tendi a chiuderti. Questi termini si usano tantissimo nei libri di self-help in inglese!",factEn:"Attachment styles theory is fundamental in psychology! 'Secure' is the healthy type. 'Anxious' is fearing losing loved ones. 'Avoidant' is when you tend to close yourself off. These terms are used a lot in English self-help books!",words:[
    {en:"secure",it:"sicuro / stabile",ex:"She has a secure attachment style."},
    {en:"anxious",it:"ansioso",ex:"I feel anxious when you don't reply."},
    {en:"avoidant",it:"evitante",ex:"He has an avoidant personality."},
    {en:"attachment",it:"attaccamento",ex:"Attachment styles form in childhood."},
    {en:"trust",it:"fiducia",ex:"Trust is the base of everything."},
    {en:"pattern",it:"schema / modello",ex:"She recognized her toxic patterns."},
    {en:"childhood",it:"infanzia",ex:"Our childhood shapes who we become."},
    {en:"emotional",it:"emotivo",ex:"She is a very emotional person."},
  ]},
  {emoji:"💕",title:"Romanzi Rosa",titleEn:"Romance Novels",fact:"I romanzi rosa sono il genere più venduto al mondo in inglese! La parola 'longing' non ha traduzione esatta: è un misto di desiderio, nostalgia e attesa. E 'swoon' — cedere per qualcuno di bello — è la reazione tipica del romance!",factEn:"Romance novels are the best-selling genre in English! 'Longing' has no exact Italian translation: a mix of desire, nostalgia and waiting. And 'swoon' — to faint from beauty — is the typical romance reaction!",words:[
    {en:"longing",it:"desiderio / nostalgia",ex:"She felt a deep longing for him."},
    {en:"tender",it:"tenero",ex:"His voice was so tender and warm."},
    {en:"whisper",it:"sussurrare",ex:"He whispered her name softly."},
    {en:"heartbeat",it:"battito del cuore",ex:"Her heartbeat was racing fast."},
    {en:"beloved",it:"amato / a",ex:"You are my beloved, always."},
    {en:"swoon",it:"svenire / cedere",ex:"She swooned at his gentle smile."},
    {en:"breathless",it:"senza fiato",ex:"His words left her breathless."},
    {en:"flutter",it:"fremito / battere",ex:"Her heart fluttered when he walked in."},
  ]},
  {emoji:"📚",title:"Nicholas Sparks",titleEn:"Nicholas Sparks",fact:"Nicholas Sparks è il re del romanzo rosa americano! 'The Notebook' (Le pagine della nostra vita) e 'A Walk to Remember' sono i suoi capolavori. La sua parola chiave? 'Devoted' — essere completamente dedicati a qualcuno per tutta la vita.",factEn:"Nicholas Sparks is the king of American romance! 'The Notebook' and 'A Walk to Remember' are his masterpieces. His keyword? 'Devoted' — being completely dedicated to someone for your whole life.",words:[
    {en:"devoted",it:"devoto / dedicato",ex:"He was devoted to her forever."},
    {en:"cherish",it:"custodire / tenere caro",ex:"I cherish every moment with you."},
    {en:"soulmate",it:"anima gemella",ex:"I think you are my soulmate."},
    {en:"timeless",it:"senza tempo / eterno",ex:"Their love was timeless."},
    {en:"promise",it:"promessa",ex:"Keep your promise, always."},
    {en:"forever",it:"per sempre",ex:"I will love you forever."},
    {en:"fate",it:"destino",ex:"It must have been fate that we met."},
    {en:"memory",it:"ricordo",ex:"I hold this memory in my heart."},
  ]},
  {emoji:"📖",title:"Colleen Hoover",titleEn:"Colleen Hoover",fact:"Colleen Hoover — chiamata 'CoHo' dai fan — è la regina del romance moderno! 'It Ends With Us', 'Ugly Love', 'November 9' — tutti bestseller mondiali. I suoi libri parlano di donne forti, amori complicati e crescita personale.",factEn:"Colleen Hoover — called 'CoHo' by fans — is the queen of modern romance! 'It Ends With Us', 'Ugly Love', 'November 9' — all worldwide bestsellers. Her books deal with strong women, complicated loves and personal growth.",words:[
    {en:"vulnerable",it:"vulnerabile",ex:"Being vulnerable takes real courage."},
    {en:"deserve",it:"meritare",ex:"You deserve so much better."},
    {en:"brave",it:"coraggioso",ex:"She was brave enough to leave."},
    {en:"overcome",it:"superare",ex:"She overcame everything alone."},
    {en:"worthy",it:"degno / che merita",ex:"You are worthy of great love."},
    {en:"growth",it:"crescita",ex:"Personal growth takes time and courage."},
    {en:"strong",it:"forte",ex:"She is stronger than she knows."},
    {en:"let go",it:"lasciar andare",ex:"Sometimes you have to let go and move on."},
  ]},
  {emoji:"💙",title:"I Tuoi Colori: Blu & Rosa",titleEn:"Your Colors: Blue & Pink",fact:"Il blu ha tantissime sfumature! 'Navy' è il blu scuro, 'sky blue' è il celeste, 'cobalt' è intenso, 'teal' è azzurro-verde. Il rosa va da 'blush' (quasi bianco) a 'fuchsia' a 'hot pink'. Il mare al tramonto le ha tutte!",factEn:"Blue has so many shades! 'Navy' is dark blue, 'sky blue' is celeste, 'cobalt' is intense blue, 'teal' is blue-green. Pink goes from 'blush' to 'fuchsia' to 'hot pink'. The sea at sunset has them all!",words:[
    {en:"navy",it:"blu marino",ex:"She wore a beautiful navy dress."},
    {en:"blush",it:"rosa pallido",ex:"The sky turned blush at sunset."},
    {en:"cobalt",it:"blu cobalto",ex:"Cobalt is a rich deep blue."},
    {en:"teal",it:"azzurro-verde",ex:"The sea was a perfect teal color."},
    {en:"fuchsia",it:"fucsia",ex:"I love her fuchsia scarf!"},
    {en:"lilac",it:"lilla",ex:"The lilac flowers smell wonderful."},
    {en:"ivory",it:"avorio",ex:"She wore an elegant ivory gown."},
    {en:"crimson",it:"cremisi / rosso intenso",ex:"The sunset turned a deep crimson."},
  ]},
  {emoji:"🌙",title:"Il Vocabolario della Luna",titleEn:"The Language of the Moon",fact:"La luna ha un vocabolario tutto suo! 'Waxing' = la luna cresce, 'waning' = diminuisce. 'Crescent' è la luna a falce. E sai che 'lunatic' — pazzo — viene proprio da 'luna'? I romani credevano che la luna piena rendesse le persone pazze!",factEn:"The moon has its own vocabulary! 'Waxing' = the moon grows, 'waning' = it shrinks. 'Crescent' is the crescent moon. Did you know 'lunatic' comes from 'luna'? Romans believed the full moon made people crazy!",words:[
    {en:"waxing",it:"crescente",ex:"The waxing moon brings new energy."},
    {en:"waning",it:"calante",ex:"The waning moon is for releasing."},
    {en:"crescent",it:"falce / mezzaluna",ex:"The crescent moon is so romantic."},
    {en:"full moon",it:"luna piena",ex:"Tonight is a magical full moon!"},
    {en:"lunar",it:"lunare",ex:"The lunar cycle lasts 28 days."},
    {en:"eclipse",it:"eclissi",ex:"The lunar eclipse was breathtaking."},
    {en:"phase",it:"fase",ex:"Each moon phase has its own energy."},
    {en:"new moon",it:"luna nuova",ex:"The new moon is perfect for intentions."},
  ]},
  {emoji:"☕",title:"Caffè & Colazione",titleEn:"Coffee & Breakfast",fact:"L'italiano ha conquistato il mondo del caffè! 'Espresso', 'cappuccino', 'latte' sono parole italiane usate ovunque. Ma in America ordinare un 'latte' significa solo latte caldo! Devi sempre dire 'coffee latte'.",factEn:"Italian conquered the coffee world! But in America ordering a 'latte' means just warm milk! You always have to say 'coffee latte'.",words:[
    {en:"sip",it:"sorso / sorseggiare",ex:"I love to sip my morning coffee."},
    {en:"brew",it:"preparare",ex:"I brew fresh coffee every morning."},
    {en:"cozy",it:"accogliente",ex:"This café feels so cozy!"},
    {en:"aroma",it:"aroma / profumo",ex:"The aroma of coffee is amazing."},
    {en:"morning routine",it:"routine mattutina",ex:"Coffee is my morning routine."},
    {en:"toast",it:"pane tostato / brindare",ex:"I make toast every single morning."},
    {en:"pastry",it:"pasticcino / brioche",ex:"I had a coffee and a pastry."},
    {en:"linger",it:"soffermarsi / stare con calma",ex:"I love to linger over my morning coffee."},
  ]},
  {emoji:"💪",title:"Il Corpo per il Pilates",titleEn:"The Body for Pilates",fact:"Per capire le lezioni di pilates in inglese è essenziale sapere le parti del corpo! L'istruttrice dirà sempre 'spine' (colonna vertebrale), 'hips' (fianchi), 'shoulders' (spalle). Studia queste e YouTube in inglese diventa facilissimo!",factEn:"To understand English pilates classes you must know body parts! The instructor will always say 'spine', 'hips', 'shoulders'. Learn these and English YouTube videos become super easy!",words:[
    {en:"spine",it:"colonna vertebrale",ex:"Lengthen your spine nice and tall."},
    {en:"hips",it:"fianchi",ex:"Open your hips wide and slow."},
    {en:"shoulders",it:"spalle",ex:"Relax your shoulders down and back."},
    {en:"stretch",it:"allungamento",ex:"This stretch feels absolutely amazing."},
    {en:"exhale",it:"espirare",ex:"Exhale and release all tension."},
    {en:"knees",it:"ginocchia",ex:"Keep your knees soft, not locked."},
    {en:"pelvis",it:"bacino",ex:"Tilt your pelvis gently forward."},
    {en:"wrists",it:"polsi",ex:"Keep your wrists straight and strong."},
  ]},
  {emoji:"🍕",title:"Cibo Italiano in Inglese",titleEn:"Italian Food in English",fact:"Tantissime parole italiane del cibo si usano in inglese senza traduzione: 'al dente', 'bruschetta', 'tiramisu', 'risotto'. Ma 'pepperoni' in America NON è il peperone! È un salame piccante. Errore classicissimo!",factEn:"Many Italian food words are used in English without translation. But 'pepperoni' in America is NOT peperone! It's a spicy salami. A very classic Italian mistake abroad!",words:[
    {en:"savory",it:"saporito / salato",ex:"This is an incredibly savory dish."},
    {en:"fresh",it:"fresco",ex:"Always use the freshest ingredients."},
    {en:"homemade",it:"fatto in casa",ex:"Homemade pasta is always the best."},
    {en:"aromatic",it:"aromatico",ex:"The tomato sauce is very aromatic."},
    {en:"indulge",it:"concedersi / viziarsi",ex:"Let's indulge in some good pasta!"},
    {en:"crispy",it:"croccante",ex:"The pizza crust is perfectly crispy."},
    {en:"drizzle",it:"condire con un filo",ex:"Drizzle some olive oil on top."},
    {en:"seasonal",it:"di stagione",ex:"Always choose seasonal vegetables."},
  ]},
  {emoji:"🌺",title:"Natura & Stagioni",titleEn:"Nature & Seasons",fact:"Le stagioni: spring (primavera), summer (estate), autumn/fall (autunno), winter (inverno). Gli americani dicono 'fall' per autunno! E 'blossom' è uno dei verbi più belli — fiorire, sbocciare. Si usa anche per le persone: 'She is blossoming.'",factEn:"Seasons: spring, summer, autumn/fall, winter. Americans say 'fall' for autumn! And 'blossom' is one of the most beautiful verbs — fiorire. Also used for people: 'She is blossoming.'",words:[
    {en:"blossom",it:"fiorire / sbocciare",ex:"She is starting to blossom."},
    {en:"breeze",it:"brezza",ex:"The sea breeze is so refreshing."},
    {en:"bloom",it:"fioritura",ex:"The flowers are in full bloom."},
    {en:"dawn",it:"alba",ex:"I watched the dawn this morning."},
    {en:"horizon",it:"orizzonte",ex:"Look at that beautiful horizon!"},
    {en:"dusk",it:"crepuscolo",ex:"The sky is pink at dusk."},
    {en:"meadow",it:"prato",ex:"We walked through a beautiful meadow."},
    {en:"foliage",it:"fogliame",ex:"The autumn foliage is breathtaking."},
  ]},
  {emoji:"😴",title:"Sogni & Benessere",titleEn:"Dreams & Wellbeing",fact:"'Wellbeing' (benessere) in inglese è una parola sola! 'Self-care' significa prendersi cura di sé. 'Daydream' è sognare ad occhi aperti. 'Hygge' è una parola danese entrata in inglese: il comfort accogliente di stare a casa al caldo.",factEn:"'Wellbeing' is one English word! 'Self-care' means prendersi cura di sé. 'Daydream' means sognare ad occhi aperti. 'Hygge' is a Danish word in English: the cozy comfort of being home and warm.",words:[
    {en:"wellbeing",it:"benessere",ex:"Your wellbeing always comes first."},
    {en:"self-care",it:"cura di sé",ex:"Self-care is never selfish."},
    {en:"daydream",it:"sognare ad occhi aperti",ex:"I love to daydream at the beach."},
    {en:"nurture",it:"nutrire / prendersi cura",ex:"Nurture your mind, body and soul."},
    {en:"restful",it:"riposante",ex:"I had the most restful sleep."},
    {en:"unwind",it:"rilassarsi",ex:"I need to unwind after work."},
    {en:"recharge",it:"ricaricarsi",ex:"A quiet evening helps me recharge."},
    {en:"mindfulness",it:"consapevolezza del momento",ex:"Mindfulness helps reduce anxiety."},
  ]},
  {emoji:"🎵",title:"Musica & Sentimenti",titleEn:"Music & Feelings",fact:"'Bittersweet' è agrodolce — gioia mista a tristezza. 'Goosebumps' (pelle d'oca) è quello che senti quando una canzone ti emoziona davvero. E 'melancholy' — malinconia — è una delle parole più belle in inglese!",factEn:"'Bittersweet' is agrodolce — joy mixed with sadness. 'Goosebumps' is pelle d'oca. And 'melancholy' — malinconia — is one of the most beautiful English words!",words:[
    {en:"bittersweet",it:"agrodolce",ex:"This song feels so bittersweet."},
    {en:"goosebumps",it:"pelle d'oca",ex:"This song gives me goosebumps!"},
    {en:"soothing",it:"calmante / rilassante",ex:"The music is very soothing."},
    {en:"melancholy",it:"malinconia",ex:"There is beauty in melancholy."},
    {en:"uplifting",it:"che tira su il morale",ex:"What an uplifting joyful song!"},
    {en:"lyrics",it:"testo della canzone",ex:"The lyrics of this song are so beautiful."},
    {en:"chorus",it:"ritornello",ex:"The chorus is the best part!"},
    {en:"nostalgic",it:"nostalgico",ex:"This song makes me feel so nostalgic."},
  ]},
  {emoji:"🚨",title:"False Friends!",titleEn:"False Friends — Attenzione!",fact:"Le 'false friends' sono parole inglesi che SEMBRANO italiane ma significano cose completamente diverse! 'Actually' NON vuol dire 'attualmente' — significa 'in realtà'! 'Library' NON è 'libreria' — è 'biblioteca'! Conoscerle ti evita figuracce imbarazzanti!",factEn:"'False friends' are English words that LOOK Italian but mean completely different things! 'Actually' does NOT mean 'attualmente' — it means 'in realtà'! 'Library' is NOT 'libreria' — it's 'biblioteca'! Knowing them saves you from embarrassing mistakes!",words:[
    {en:"actually",it:"⚠️ IN REALTÀ (≠ attualmente!)",ex:"Actually, I love Italian food!"},
    {en:"eventually",it:"⚠️ ALLA FINE (≠ eventualmente!)",ex:"Eventually she learned English."},
    {en:"library",it:"⚠️ BIBLIOTECA (≠ libreria!)",ex:"I found this at the library."},
    {en:"sensible",it:"⚠️ RAGIONEVOLE (≠ sensibile!)",ex:"That was a very sensible choice."},
    {en:"sympathetic",it:"⚠️ COMPRENSIVO (≠ simpatico!)",ex:"She was very sympathetic."},
    {en:"embarrassed",it:"⚠️ IMBARAZZATO (≠ incinta!)",ex:"I was so embarrassed when I fell."},
    {en:"argument",it:"⚠️ LITIGIO (≠ argomento!)",ex:"We had a small argument yesterday."},
    {en:"pretend",it:"⚠️ FINGERE (≠ pretendere!)",ex:"She pretended she didn't hear me."},
  ]},
  {emoji:"💬",title:"Frasi Pratiche",titleEn:"Everyday English Phrases",fact:"Queste sono le frasi che si usano DAVVERO nella vita quotidiana in inglese! Al ristorante, in viaggio, con colleghi stranieri. Imparare frasi complete vale più di 50 parole isolate — sono pronte da usare subito!",factEn:"These are the phrases ACTUALLY used in daily English life! At restaurants, traveling, with foreign colleagues. Learning complete phrases is worth more than isolated words — they're ready to use immediately!",words:[
    {en:"Can I have the bill, please?",it:"Posso avere il conto, per favore?",ex:"Waiter! Can I have the bill, please?"},
    {en:"Could you repeat that, please?",it:"Puoi ripetere, per favore?",ex:"Sorry, could you repeat that slowly?"},
    {en:"How much does it cost?",it:"Quanto costa?",ex:"Excuse me, how much does this cost?"},
    {en:"I don't understand, sorry.",it:"Non capisco, mi dispiace.",ex:"I don't understand. Can you help me?"},
    {en:"Nice to meet you!",it:"Piacere di conoscerti!",ex:"Hi, I'm Emanuela! Nice to meet you!"},
    {en:"Could you speak more slowly?",it:"Puoi parlare più lentamente?",ex:"Sorry, could you speak more slowly?"},
    {en:"Where is the nearest...?",it:"Dov'è il/la più vicino/a...?",ex:"Where is the nearest pharmacy?"},
    {en:"I would like to book a table.",it:"Vorrei prenotare un tavolo.",ex:"Hi, I would like to book a table for two."},
  ]},
  {emoji:"📅",title:"Numeri & Giorni",titleEn:"Numbers & Days",fact:"I giorni della settimana in inglese vengono da divinità nordiche e romane! Monday = Luna (Moon-day), Thursday = Thor (dio del tuono), Friday = Freya (dea dell'amore), Saturday = Saturno. E December viene da 'decem' — dieci in latino, perché era il decimo mese del calendario romano!",factEn:"English days of the week come from Nordic and Roman deities! Monday = Moon-day, Thursday = Thor, Friday = Freya (goddess of love). And December comes from 'decem' — ten in Latin, because it was the 10th month of the Roman calendar!",words:[
    {en:"Monday / Friday",it:"Lunedì / Venerdì",ex:"I have pilates on Monday and Friday."},
    {en:"weekend",it:"fine settimana",ex:"I love weekends at the beach!"},
    {en:"January / December",it:"Gennaio / Dicembre",ex:"My birthday is in December! ♐"},
    {en:"first / second / third",it:"primo / secondo / terzo",ex:"She lives on the third floor."},
    {en:"once / twice / always",it:"una volta / due volte / sempre",ex:"I practice pilates twice a week."},
    {en:"schedule",it:"programma / orario",ex:"What's on your schedule today?"},
    {en:"deadline",it:"scadenza",ex:"The deadline is next Friday."},
    {en:"appointment",it:"appuntamento",ex:"I have a doctor's appointment tomorrow."},
  ]},
  {emoji:"✈️",title:"Viaggiare in Inglese",titleEn:"Travel English",fact:"Saper parlare inglese in aeroporto ti salva la vita! 'Boarding pass' è la carta d'imbarco, 'luggage' sono i bagagli, 'check-in' lo conosci già! E se senti 'Last call for boarding' — corri, è l'ultimo avviso per salire sull'aereo!",factEn:"Knowing English at the airport is a lifesaver! 'Boarding pass' = carta d'imbarco, 'luggage' = bagagli, 'check-in' you already know! And if you hear 'Last call for boarding' — run, it's the last warning to board!",words:[
    {en:"boarding pass",it:"carta d'imbarco",ex:"Please have your boarding pass ready."},
    {en:"luggage",it:"bagagli",ex:"My luggage is on the conveyor belt."},
    {en:"departure",it:"partenza",ex:"What time is your departure?"},
    {en:"arrival",it:"arrivo",ex:"The arrival time is 10pm."},
    {en:"passport",it:"passaporto",ex:"Don't forget your passport!"},
    {en:"customs",it:"dogana",ex:"We have to go through customs first."},
    {en:"delay",it:"ritardo",ex:"The flight is delayed by two hours."},
    {en:"destination",it:"destinazione",ex:"What is your final destination?"},
  ]},
  {emoji:"👗",title:"Moda & Stile",titleEn:"Fashion & Style",fact:"La moda italiana è famosa in tutto il mondo, ma i termini del settore si usano molto in inglese! 'Outfit' è l'insieme di capi che indossi, 'accessory' è un accessorio, 'trendy' significa di moda. E 'vintage' è la stessa parola in entrambe le lingue!",factEn:"Italian fashion is world famous, but industry terms are mostly English! 'Outfit' is what you're wearing, 'accessory' = accessorio, 'trendy' means di moda. And 'vintage' is the same in both languages!",words:[
    {en:"outfit",it:"completo / insieme",ex:"I love your outfit today!"},
    {en:"trendy",it:"alla moda",ex:"That bag is so trendy right now."},
    {en:"accessory",it:"accessorio",ex:"The right accessory changes everything."},
    {en:"vintage",it:"vintage",ex:"She found a beautiful vintage dress."},
    {en:"wardrobe",it:"guardaroba",ex:"I need to refresh my wardrobe."},
    {en:"fabric",it:"tessuto",ex:"This fabric is so soft and luxurious."},
    {en:"tailored",it:"su misura / sartoriale",ex:"She wore a perfectly tailored blazer."},
    {en:"chic",it:"chic / elegante",ex:"The look is effortlessly chic."},
  ]},
  {emoji:"💌",title:"Amicizia",titleEn:"Friendship",fact:"In inglese ci sono parole bellissime per descrivere l'amicizia! 'Bestie' è il termine informale per migliore amica. 'Ride or die' significa un'amica fedele in ogni situazione. E 'soul sister' è una vera sorella d'anima — un'amica che senti parte di te!",factEn:"English has beautiful words for friendship! 'Bestie' is the informal term for best friend. 'Ride or die' means a loyal friend in any situation. And 'soul sister' is a true soul sister — a friend you feel is part of you!",words:[
    {en:"bestie",it:"migliore amica",ex:"She is my absolute bestie."},
    {en:"bond",it:"legame",ex:"We have such a strong bond."},
    {en:"loyal",it:"leale / fedele",ex:"A loyal friend is a treasure."},
    {en:"support",it:"supporto / sostenere",ex:"Thank you for your endless support."},
    {en:"soul sister",it:"sorella d'anima",ex:"She is my soul sister, always."},
    {en:"inside joke",it:"battuta tra di noi",ex:"We have so many inside jokes!"},
    {en:"check in",it:"controllare come stai",ex:"I always check in on my friends."},
    {en:"unconditional",it:"incondizionato",ex:"True friendship is unconditional."},
  ]},
  {emoji:"🌍",title:"Emozioni in Inglese",titleEn:"Emotions in English",fact:"L'inglese ha parole per emozioni che l'italiano non ha! 'Overwhelmed' significa sopraffatta da tutto — troppo da gestire. 'Grateful' è grata. 'Content' non è contento eccitato, ma quella pace profonda di quando tutto va bene. Impara queste parole e potrai esprimere tutto!",factEn:"English has words for emotions Italian doesn't! 'Overwhelmed' means sopraffatta — too much to handle. 'Grateful' = grata. 'Content' is not excited happiness but the deep peace of when everything is okay. Learn these and you can express everything!",words:[
    {en:"overwhelmed",it:"sopraffatta / sommersa",ex:"I feel completely overwhelmed today."},
    {en:"grateful",it:"grata / riconoscente",ex:"I am so grateful for this moment."},
    {en:"content",it:"appagata / in pace",ex:"I feel truly content with my life."},
    {en:"proud",it:"orgogliosa",ex:"I am so proud of everything you do."},
    {en:"relieved",it:"sollevata",ex:"I felt so relieved after the test."},
    {en:"hopeful",it:"speranzosa",ex:"I feel hopeful about the future."},
    {en:"at peace",it:"in pace",ex:"I finally feel at peace with myself."},
    {en:"excited",it:"entusiasta / emozionata",ex:"I am so excited for tomorrow!"},
  ]},
];

const TV=[
  {show:"The Good Place",emoji:"😇",phrases:[
    {en:"Everything is fine.",it:"Va tutto bene.",note:"Usata in modo ironico — la situazione NON va bene per niente! 😄"},
    {en:"You are a good person.",it:"Sei una brava persona.",note:"Una delle frasi più belle e toccanti dell'intera serie."},
    {en:"What the fork?!",it:"Ma cosa cavolo?!",note:"Fork = forchetta, ma qui sostituisce una parolaccia in modo geniale!"},
    {en:"I need to think about this.",it:"Ho bisogno di rifletterci.",note:"Utilissima nella vita reale — prenditi il tuo tempo!"},
    {en:"I want to be a better person.",it:"Voglio essere una persona migliore.",note:"Il cuore dell'intera serie in una frase."},
    {en:"We can figure this out together.",it:"Possiamo capirlo insieme.",note:"'Figure out' = capire/risolvere. Usatissima!"},
    {en:"I made a mistake.",it:"Ho fatto un errore.",note:"Importante saperla dire — tutti sbagliano!"},
    {en:"This is a beautiful place.",it:"Questo è un posto bellissimo.",note:"Semplice, chiara, usabile ovunque."},
  ]},
  {show:"Ginny & Georgia",emoji:"💅",phrases:[
    {en:"I can handle it.",it:"Riesco a gestirlo.",note:"'Handle' = gestire. Un'espressione molto americana e decisa!"},
    {en:"Are you okay?",it:"Stai bene?",note:"La frase più utile in assoluto in inglese. Imparala per prima!"},
    {en:"I'm figuring it out.",it:"Sto capendo come fare.",note:"'Figure out' = capire/risolvere. Si usa tantissimo."},
    {en:"She is my family.",it:"Lei è la mia famiglia.",note:"Bello da usare con le amiche del cuore."},
    {en:"I feel lost.",it:"Mi sento persa.",note:"'Lost' = perso/a. Si usa tanto in senso figurato."},
    {en:"We can do this together.",it:"Possiamo farcela insieme.",note:"Motivazionale e bellissima!"},
    {en:"I just need some space.",it:"Ho solo bisogno di spazio.",note:"Fondamentale saper dire i propri bisogni."},
    {en:"You have no idea what I've been through.",it:"Non sai cosa ho passato.",note:"Drammatica ma utilissima — usata tantissimo!"},
  ]},
  {show:"Bridgerton",emoji:"🌹",phrases:[
    {en:"I burn for you.",it:"Brucio per te.",note:"La frase più famosa di Simon — pura poesia romantica!"},
    {en:"You are the most beautiful woman in the room.",it:"Sei la donna più bella della stanza.",note:"Elegante e romantica — usabile ovunque! 😄"},
    {en:"My heart belongs to you.",it:"Il mio cuore ti appartiene.",note:"Classico romanzo rosa in cinque parole."},
    {en:"I cannot imagine a world without you.",it:"Non riesco a immaginare un mondo senza di te.",note:"Lunga ma bellissima — imparala per gradi!"},
    {en:"You have bewitched me.",it:"Mi hai stregato/a.",note:"'Bewitch' = stregare. Parola magica!"},
    {en:"Shall we dance?",it:"Balliamo?",note:"Elegante e classica — perfetta per una festa!"},
    {en:"I have never felt this way before.",it:"Non ho mai provato una cosa del genere.",note:"Romantica e utilissima nella vita reale."},
    {en:"You are unlike anyone I have ever met.",it:"Sei diversa da chiunque io abbia mai incontrato.",note:"Il massimo complimento!"},
  ]},
  {show:"Outer Banks",emoji:"🏄",phrases:[
    {en:"We are the Pogues.",it:"Siamo i Pogues.",note:"'Pogues' è il nome del gruppo di amici — usa 'We are' per presentare te e i tuoi amici!"},
    {en:"I'm not gonna give up on you.",it:"Non ti abbandonerò.",note:"'Give up on someone' = abbandonare qualcuno. 'Gonna' è il colloquiale americano di 'going to'."},
    {en:"She is my person.",it:"Lei è la mia persona.",note:"Frase iconica usata anche in Grey's Anatomy — indica la persona più importante della tua vita!"},
    {en:"Stay gold.",it:"Rimani autentica.",note:"'Gold' qui non è l'oro — significa puro e autentico. Viene da una poesia di Robert Frost!"},
    {en:"I'll always come back to you.",it:"Tornerò sempre da te.",note:"'I'll' = I will. Una delle promesse più romantiche in inglese — perfetta per Bridgerton! 🌹"},
    {en:"We're not done yet.",it:"Non abbiamo ancora finito.",note:"'Done' = finito. 'Not done yet' = non ancora finito. Si usa tantissimo nella vita reale!"},
    {en:"The treasure is real.",it:"Il tesoro è reale.",note:"'Real' = reale/vero. Attenzione: 'really' come avverbio significa 'davvero'!"},
    {en:"I trust you with my life.",it:"Ti affido la mia vita.",note:"'Trust someone with something' = fidarsi di qualcuno per qualcosa. Bella e intensa!"},
  ]},
  {show:"Never Have I Ever",emoji:"🌸",phrases:[
    {en:"You deserve good things.",it:"Meriti cose belle.",note:"'Deserve' = meritare. Una delle parole più belle in inglese — usala con te stessa ogni giorno!"},
    {en:"I'm going to have a great year.",it:"Avrò un anno fantastico.",note:"'Going to' si usa per piani certi. 'Great' = fantastico. Dillo ogni mattina allo specchio!"},
    {en:"Stop trying to be perfect.",it:"Smettila di cercare di essere perfetta.",note:"'Stop + -ing' = smettila di fare qualcosa. Una struttura importantissima in inglese!"},
    {en:"It's okay to ask for help.",it:"Va bene chiedere aiuto.",note:"'It's okay to...' + verbo infinito. Formula utilissima — impara questa struttura!"},
    {en:"You matter to me.",it:"Sei importante per me.",note:"'To matter' NON è 'materia'! Significa essere importante. 'You matter' è bellissima!"},
    {en:"She is stronger than she thinks.",it:"È più forte di quanto pensi.",note:"'Stronger than...' = più forte di... I comparativi in inglese si fanno con -er o 'more'!"},
    {en:"I don't know how to do this.",it:"Non so come farlo.",note:"'I don't know how to...' + infinito. Una delle strutture più utili dell'inglese quotidiano!"},
    {en:"Give yourself a chance.",it:"Datti una possibilità.",note:"'Give yourself a chance' = datti una possibilità. Anche 'give someone a chance' = dare una chance!"},
  ]},
  {show:"Wednesday",emoji:"🖤",phrases:[
    {en:"I don't have friends. I have accomplices.",it:"Non ho amici. Ho complici.",note:"Frase iconica di Wednesday! 'Accomplice' = complice. Molto più intrigante di 'friend'! 🖤"},
    {en:"Normal is an illusion.",it:"Il normale è un'illusione.",note:"'Illusion' = illusione — stessa parola! E 'normal' si pronuncia NOR-mal."},
    {en:"I like to follow my own path.",it:"Mi piace seguire la mia strada.",note:"'Follow your own path' = seguire la propria strada. Frase motivazionale bellissima!"},
    {en:"Don't underestimate me.",it:"Non sottovalutarmi.",note:"'Underestimate' = sottovalutare. 'Under' in inglese spesso significa 'sotto' o 'meno del dovuto'."},
    {en:"The truth always comes out.",it:"La verità viene sempre a galla.",note:"'Come out' = venire fuori. 'The truth comes out' — si usa tantissimo nelle serie!"},
    {en:"My gift is also my curse.",it:"Il mio dono è anche la mia maledizione.",note:"'Gift' = dono. 'Curse' = maledizione. Perfetto per chi ama cristalli e magia! 💜"},
    {en:"I am an acquired taste.",it:"Sono un gusto acquisito.",note:"'Acquired taste' = qualcosa che non piace subito ma si impara ad apprezzare. Elegantissima!"},
    {en:"I don't need your approval.",it:"Non ho bisogno della tua approvazione.",note:"'Approval' = approvazione. 'I don't need' = non ho bisogno. Usatissima — e molto Wednesday!"},
  ]},
  {show:"Heartstopper",emoji:"🍂",phrases:[
    {en:"I just want to be happy.",it:"Voglio solo essere felice.",note:"'Just' qui significa 'semplicemente'. 'I just want to...' = voglio solo... Dolcissima!"},
    {en:"You are not alone.",it:"Non sei sola.",note:"Una delle frasi più importanti in inglese. Semplice, potentissima, sempre utile."},
    {en:"It's okay to be yourself.",it:"Va bene essere se stessi.",note:"'Be yourself' = essere se stessi. Una delle prime cose da imparare in inglese!"},
    {en:"You make me feel like myself.",it:"Mi fai sentire me stessa.",note:"'Make someone feel' = far sentire qualcuno. Struttura bellissima e romantica!"},
    {en:"You are enough.",it:"Sei abbastanza.",note:"'Enough' = abbastanza. Due parole, significato immenso. Tatuatela! 🌸"},
    {en:"Friendship is everything.",it:"L'amicizia è tutto.",note:"'Friendship' = amicizia — si forma da 'friend' + '-ship'. Tanti sostantivi astratti finiscono così!"},
    {en:"Just breathe.",it:"Respira soltanto.",note:"Semplice e potente! Perfetta anche durante il pilates — 'just breathe, engage your core!' 🧘"},
    {en:"I think about you all the time.",it:"Penso a te continuamente.",note:"'All the time' = sempre, continuamente. Molto più enfatico di 'always' — super romantico!"},
  ]},
  {show:"Grey's Anatomy",emoji:"🏥",phrases:[
    {en:"She is my person.",it:"Lei è la mia persona.",note:"La frase iconica di Meredith e Cristina — indica la persona più importante della tua vita!"},
    {en:"It's a beautiful day to save lives.",it:"È una bella giornata per salvare vite.",note:"La frase di apertura del dottor Sheperd. 'To save' = salvare. Bella da usare ogni mattina!"},
    {en:"Have some fire. Be unstoppable.",it:"Abbi del fuoco dentro. Sii inarrestabile.",note:"'Unstoppable' = inarrestabile. 'Fire' qui non è fuoco letterale — è passione e determinazione!"},
    {en:"I am the sun.",it:"Io sono il sole.",note:"Cristina a Meredith — quando qualcuno ti oscura, ricordati chi sei. Potentissima!"},
    {en:"Don't let what he wants eclipse what you need.",it:"Non lasciare che quello che vuole lui eclissi quello di cui hai bisogno.",note:"'Eclipse' = eclissare. Perfetta parola per chi ama la luna! 🌙"},
    {en:"You're my best friend.",it:"Sei la mia migliore amica.",note:"'Best friend' = migliore amica. 'Best' = il/la migliore. Semplicissima e bellissima!"},
    {en:"I have to believe that the best is still out there.",it:"Devo credere che il meglio debba ancora arrivare.",note:"'Still out there' = ancora là fuori, non ancora arrivato. Molto ottimista!"},
    {en:"We have to be our own kind of normal.",it:"Dobbiamo essere la nostra versione del normale.",note:"'Our own kind of' = la nostra versione di. Struttura bellissima e adattabile!"},
  ]},
  {show:"Emily in Paris",emoji:"🗼",phrases:[
    {en:"Paris is always a good idea.",it:"Parigi è sempre una buona idea.",note:"La citazione più famosa su Parigi — perfetta per Instagram! 📸"},
    {en:"I don't speak French, but I speak fashion.",it:"Non parlo francese, ma parlo di moda.",note:"Usa 'I speak + something' in senso figurato — significa capire qualcosa profondamente!"},
    {en:"Every day is a chance to reinvent yourself.",it:"Ogni giorno è un'occasione per reinventarsi.",note:"'Reinvent yourself' = reinventarsi. 'Every day is a chance to...' = ogni giorno è un'occasione per..."},
    {en:"You only get one first impression.",it:"Hai solo una prima impressione.",note:"'First impression' = prima impressione. 'You only get one' = ne hai soltanto una!"},
    {en:"I came here to work, not to make friends.",it:"Sono venuta qui per lavorare, non per fare amicizie.",note:"'To make friends' = fare amicizia. Alla fine Emily fa entrambe le cose! 😄"},
    {en:"Life is short. Eat the croissant.",it:"La vita è breve. Mangia il croissant.",note:"'Life is short' = la vita è breve. Una delle frasi più usate in inglese per giustificare qualcosa!"},
    {en:"I love it here, even when it's hard.",it:"Amo questo posto, anche quando è difficile.",note:"'Even when it's hard' = anche quando è difficile. 'Even when' è una struttura molto utile!"},
    {en:"The best things in life are unexpected.",it:"Le cose migliori della vita sono inaspettate.",note:"'Unexpected' = inaspettato. 'The best things in life are...' — struttura bellissima e flessibile!"},
  ]},
  {show:"One Tree Hill",emoji:"🌳",phrases:[
    {en:"One day you'll leave this world behind.",it:"Un giorno lascerai questo mondo.",note:"Dall'intro della serie — poetica e intensa. 'Leave behind' = lasciare alle spalle."},
    {en:"It's the oldest story in the world.",it:"È la storia più vecchia del mondo.",note:"'The oldest story in the world' = una situazione che si ripete nella storia dell'umanità."},
    {en:"Lucas, I'm the girl for you.",it:"Lucas, sono la ragazza giusta per te.",note:"Memorabile dichiarazione di Peyton. 'The girl for you' = la ragazza giusta per te!"},
    {en:"Don't say I never gave you anything.",it:"Non dire che non ti ho mai dato niente.",note:"'Don't say I never...' = non dire che non ho mai... Ironica e usatissima tra amici!"},
    {en:"People always leave.",it:"Le persone se ne vanno sempre.",note:"La frase di Peyton. 'Leave' = andarsene. Triste ma realistica — usata anche nella vita reale!"},
    {en:"Find something you're passionate about.",it:"Trova qualcosa per cui sei appassionata.",note:"'Passionate about' = appassionata di. Struttura importantissima: 'I'm passionate about...'"},
    {en:"The rest of your life is being shaped right now.",it:"Il resto della tua vita si sta formando adesso.",note:"'Being shaped' = si sta formando / plasmando. Il gerundio passivo — struttura avanzata!"},
    {en:"You're not alone in this.",it:"Non sei sola in questo.",note:"'You're not alone in this' = non sei sola in questa situazione. Diversa da 'you're not alone'!"},
  ]},
];

const PROVERBS=[
  {en:"Every cockroach is pretty to his mother",
   nap:"Ogn scarrafon è bell a mamma soij",
   it:"Ogni scarafaggio è bello per la sua mamma",
   meaning:"Ogni madre vede sempre il meglio nei suoi figli — non importa come siano agli occhi degli altri. L'amore materno è cieco e bellissimo!",
   meaningEn:"Every mother always sees the best in her children — no matter how they appear to others. A mother's love is beautifully blind!",
   words:[
     {en:"cockroach",it:"scarafaggio",ex:"Every cockroach is pretty to his mother."},
     {en:"pretty",it:"bello / carino",ex:"The moonlight looks so pretty tonight."},
     {en:"mother",it:"madre / mamma",ex:"My mother always believes in me."},
   ]},
  {en:"When devil caresses you, he wants the soul",
   nap:"Quand o riavl taccarezz, l'anim va truvann",
   it:"Quando il diavolo ti accarezza, vuole l'anima",
   meaning:"Quando qualcuno è troppo gentile senza motivo, di solito vuole qualcosa in cambio. Stai attenta a chi ti riempie di attenzioni improvvise!",
   meaningEn:"When someone is unusually kind for no reason, they usually want something in return. Beware of people who suddenly shower you with attention!",
   words:[
     {en:"devil",it:"diavolo",ex:"When devil caresses you, be careful."},
     {en:"caress",it:"accarezzare",ex:"She caressed the crystal gently."},
     {en:"soul",it:"anima",ex:"Moonstone connects to your soul."},
   ]},
  {en:"The father father of the water",
   nap:"O patpa re l'acqu",
   it:"Il padre padre dell'acqua (non lo so non ha molto senso in italiano)",
   meaning:"Quando piove tanto, ma proprio tanto, ma proprio tantoooooo",
   meaningEn:"When it rains a lot, but really a lot, but really a looooooot",
   words:[
     {en:"father",it:"padre",ex:"The father father of the water."},
     {en:"water",it:"acqua",ex:"The water flows down the mountain."},
   ]},
  {en:"Neither the dogs!",
   nap:"manc e can!",
   it:"Neanche i cani!",
   meaning:"Quando una persona di dice di fare qualcosa che non faresti mai, e tu rispondi 'neanche i cani!' per dire che è una cosa così brutta che neanche i cani la farebbero.",
   meaningEn:"When someone tells you to do something you would never do, and you respond 'neanche i cani!' to say it's such a bad thing that not even dogs would do it.",
   words:[
     {en:"neither",it:"nemmeno",ex:"Neither the dogs!"},
     {en:"dogs",it:"cani",ex:"Neither the dogs!"},
   ]},
  {en:"Who cries fucks who laughs",
   nap:"Chi chiagne fott chi rir",
   it:"Chi piange fotte chi ride",
   meaning:"lamentarsi è spesso un metodo efficace per manipolare l'altrui pietà e ottenere ciò che si vuole, a scapito di chi vive con più dignità e silenzio.",
   meaningEn:"complaining is often an effective method to manipulate others' pity and get what you want, at the expense of those who live with more dignity and silence.",
   words:[
     {en:"cries",it:"piange",ex:"Who cries fucks who laughs"},
     {en:"laughs",it:"ride",ex:"Who cries fucks who laughs"},
   ]},
  {en:"You look like the pussy's sister",
   nap:"Par a sor ra fess",
   it:"Sembri la sorella della vagina",
   meaning:"Viene utilizzata principalmente come insulto per definire una persona poco sveglia, stupida, sbadata o ridicola, con particolare riferimento alle donne (per gli uomini si usa la variante par o frat ro cazz, ovvero sembri il fratello del pene, ma questo ne parleremo più in là)",
   meaningEn:"It is mainly used as an insult to define a person who is not very bright, stupid, careless or ridiculous, with particular reference to women (for men, the variant 'par o frat ro cazz' is used, meaning 'you look like the brother of the penis', but we will discuss this later)",
   words:[
     {en:"pussy",it:"vagina",ex:"You look like the pussy's sister(fun fact: pussy also means cat)"},
     {en:"sister",it:"sorella",ex:"I have an annoying sister"},
     {en:"to look like",it:"sembri",ex:"You look like you need a drink"},
   ]},
  {en:"The sea doesn't want the drowned",
   nap:"O mar nun vò muort",
   it:"Il mare non vuole i morti",
   meaning:"Quando il mare è agitato e pericoloso, i marinai dicono che 'il mare non vuole i morti' — significa che il mare rigetta chi non lo rispetta. Si usa anche per dire che chi è già in guai profondi non trova nemmeno la pace!",
   meaningEn:"When the sea is rough and dangerous, sailors say 'the sea doesn't want the drowned' — meaning the sea rejects those who disrespect it. Also used to say that someone who is already in deep trouble can't even find peace!",
   words:[
     {en:"drown",it:"annegare",ex:"Don't drown in your own worries."},
     {en:"respect",it:"rispetto",ex:"Always have respect for the sea."},
     {en:"rough",it:"agitato / mosso",ex:"The sea is very rough today."},
   ]},
];

const LEVELS=[
  {name:"Principiante",icon:"🌱",max:50},
  {name:"Esploratrice",icon:"🌿",max:150},
  {name:"Lettrice",icon:"📚",max:300},
  {name:"Saggia",icon:"⭐",max:500},
  {name:"Maestra",icon:"🌕",max:Infinity},
];

const ACHIEVEMENTS=[
  {id:"first_word",icon:"🌱",title:"Prima Parola!",desc:"Hai imparato la tua prima parola in inglese!"},
  {id:"ten_words",icon:"✨",title:"10 Parole!",desc:"Stai crescendo velocemente!"},
  {id:"fifty_words",icon:"💫",title:"50 Parole!",desc:"Sei a metà strada — ottimo lavoro!"},
  {id:"hundred_words",icon:"🌟",title:"100 Parole!",desc:"Sei incredibile — quasi una maestra!"},
  {id:"perfect_quiz",icon:"💯",title:"Quiz Perfetta!",desc:"10/10 corrette — straordinaria!"},
  {id:"streak_3",icon:"🔥",title:"3 giorni di fila!",desc:"La costanza è la chiave del successo!"},
  {id:"streak_7",icon:"🔥🔥",title:"7 giorni di fila!",desc:"Una settimana intera! Bravissima!"},
  {id:"full_moon",icon:"🌕",title:"Luna Piena!",desc:"Hai raggiunto 100 XP — fantastica!"},
  {id:"daily_done",icon:"📅",title:"Prima Sfida del Giorno!",desc:"Prima sfida quotidiana completata!"},
  {id:"master",icon:"👑",title:"Maestra!",desc:"Hai raggiunto il livello massimo — leggendaria!"},
  {id:"false_friend",icon:"🚨",title:"Amica dei False Friends!",desc:"Hai imparato i false friends più insidiosi!"},
];

const MOON=["🌑","🌒","🌓","🌔","🌕"];
const NOTIF_MSGS=["Scus giovane ma na perzion e pataetin quand a puort? ✨ Quan sarapn salam e prosutt zij Nicol acop e zij Nicol a sott.","Signoraaa i limoniiii","comm Ann fatt lor ann fatt padron iesc for chest è 🌸 AIII","Una nuova parola al giorno fa miracoli! come Kociack e maioe","Hey Emanuela! ⭐ Il tuo segno dice: te a mettr a frecc quand s gir!","quand s zapp e s pot zij Nicol nu ten nipot."];
